name: FailAnnounce
main: me.everdras.failannounce.FailAnnounce
version: 0.2.0
commands:
    fail:
        description: Indicates a failure
        usage: /fail or /fail name
        aliases: [echoue, échoue, epicfail]
    win:
        description: Indicates a win
        usage: /win other
        aliases: [gagne, réussis, reussis]
    fa:
        description: sets options and such
        usage: /fa ignoreDefaults true/false